
// ═══════════════════════════════════════════════════════════════════════════
//  DATA — generated by build.py from the two Walmart DMP exports and Frank's
//  data/archive/daily.csv + framework DATA block. Do not hand-edit.
// ═══════════════════════════════════════════════════════════════════════════
const P = /*__PAYLOAD__*/null;

// ═══ helpers ════════════════════════════════════════════════════════════════
const DAY = 864e5;
const dayNum = s => Date.UTC(+s.slice(0, 4), +s.slice(5, 7) - 1, +s.slice(8, 10)) / DAY;
const isoOf = n => new Date(n * DAY).toISOString().slice(0, 10);
const monthOf = n => new Date(n * DAY).getUTCMonth() + 1;
const yearOf = n => new Date(n * DAY).getUTCFullYear();
const dim = (y, m) => new Date(Date.UTC(y, m, 0)).getUTCDate();
const MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const TIERS = ['low', 'mid', 'high'];
const TIER_LABEL = {low: 'Low', mid: 'Mid', high: 'High'};
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sum = a => a.reduce((x, y) => x + y, 0);
const clamp = (x, a, b) => Math.max(a, Math.min(b, x));

// Python's round() is banker's rounding; the tranche offsets are the one place a .5
// arises, so match forecast.py here (copied from Frank's JS).
function pyRound(x) {
  const f = Math.floor(x);
  if (Math.abs(x - f - 0.5) > 1e-9) return Math.round(x);
  return f % 2 === 0 ? f : f + 1;
}

// A daily series: {start, arr}. get() is O(1) by day offset; sums are inclusive.
function mkSeries(start, arr) {
  const s0 = dayNum(start);
  const S = {
    start, arr, s0, end: isoOf(s0 + arr.length - 1),
    get(iso) { const i = dayNum(iso) - s0; return i >= 0 && i < arr.length ? arr[i] : null; },
    getN(n) { const i = n - s0; return i >= 0 && i < arr.length ? arr[i] : null; },
    has(iso) { const i = dayNum(iso) - s0; return i >= 0 && i < arr.length; },
    sum(a, b) { let t = 0; for (let n = dayNum(a); n <= dayNum(b); n++) { const v = S.getN(n); if (v != null) t += v; } return t; },
    count(a, b) { let c = 0; for (let n = dayNum(a); n <= dayNum(b); n++) if (S.getN(n) != null) c++; return c; },
  };
  return S;
}

// Impute a zero-visit day (an export gap, not a day with no traffic) as the mean
// of its neighbours. GMV and orders on those days are non-zero, so the zero is
// the gap, not the truth. Flagged on the Assumptions tab.
function imputeZeros(arr) {
  const out = arr.slice(); const fixed = [];
  for (let i = 0; i < out.length; i++) if (!out[i]) {
    const a = out[i - 1] || 0, b = out[i + 1] || 0; out[i] = a && b ? (a + b) / 2 : (a || b); fixed.push(i);
  }
  return {arr: out, fixed};
}

// ═══ Walmart series ═════════════════════════════════════════════════════════
const WM = (() => {
  const sv = imputeZeros(P.seo.visits), av = imputeZeros(P.aeo.visits);
  return {
    seo: {visits: mkSeries(P.seo.start, sv.arr), rawVisits: mkSeries(P.seo.start, P.seo.visits),
          gmv: mkSeries(P.seo.start, P.seo.gmv), orders: mkSeries(P.seo.start, P.seo.orders), imputed: sv.fixed.map(i => isoOf(dayNum(P.seo.start) + i))},
    aeo: {visits: mkSeries(P.aeo.start, av.arr), gmv: mkSeries(P.aeo.start, P.aeo.gmv), orders: mkSeries(P.aeo.start, P.aeo.orders),
          imputed: av.fixed.map(i => isoOf(dayNum(P.aeo.start) + i))},
  };
})();
const GSC = {
  anon: mkSeries(P.gsc.start, P.gsc.anon), brand: mkSeries(P.gsc.start, P.gsc.brand), nonbrand: mkSeries(P.gsc.start, P.gsc.nonbrand),
  total: mkSeries(P.gsc.start, P.gsc.anon.map((v, i) => v + P.gsc.brand[i] + P.gsc.nonbrand[i])),
};
const BING = {clicks: mkSeries(P.bing.start, P.bing.clicks)};
const LAST_WM = WM.seo.visits.end;          // 2026-09-07
const LAST_GSC = GSC.total.end;             // 2026-08-09
const LAST_BING = BING.clicks.end;          // 2026-08-08

// Year-over-year the way Walmart's own export does it: the "Ly Dt" column sits
// exactly 364 days back, so weekdays align. Every YoY figure on this page uses 364.
const YOY = 364;
function yoyWindow(series, endISO, days) {
  const e = dayNum(endISO), a = isoOf(e - days + 1);
  const recent = series.sum(a, endISO), prior = series.sum(isoOf(e - days + 1 - YOY), isoOf(e - YOY));
  return {recent, prior, change: prior ? recent / prior - 1 : null, from: a, to: endISO};
}
function ratioYoy(num, den, endISO, days) {
  const n = yoyWindow(num, endISO, days), d = yoyWindow(den, endISO, days);
  const r = d.recent ? n.recent / d.recent : 0, p = d.prior ? n.prior / d.prior : 0;
  return {recent: r, prior: p, change: p ? r / p - 1 : null};
}
// Monthly rollup of a set of series over a date range → [{ym, y, m, days, ...sums}]
function monthly(seriesMap, from, to) {
  const out = [], idx = {};
  for (let n = dayNum(from); n <= dayNum(to); n++) {
    const y = yearOf(n), m = monthOf(n), key = y + '-' + String(m).padStart(2, '0');
    if (!idx[key]) { idx[key] = {ym: key, y, m, days: 0}; for (const k in seriesMap) idx[key][k] = 0; out.push(idx[key]); }
    const row = idx[key]; let any = false;
    for (const k in seriesMap) { const v = seriesMap[k].getN(n); if (v != null) { row[k] += v; any = true; } }
    if (any) row.days++;
  }
  return out;
}
// Weekly rollup ending Saturday (Walmart's scorecard weeks end on a Saturday).
function weeklySat(seriesMap, from, to) {
  const out = []; let cur = null;
  for (let n = dayNum(from); n <= dayNum(to); n++) {
    const dow = new Date(n * DAY).getUTCDay();          // 0 = Sun … 6 = Sat
    if (!cur || dow === 0) { cur = {start: isoOf(n), end: null, days: 0}; for (const k in seriesMap) cur[k] = 0; out.push(cur); }
    let any = false;
    for (const k in seriesMap) { const v = seriesMap[k].getN(n); if (v != null) { cur[k] += v; any = true; } }
    if (any) cur.days++; cur.end = isoOf(n);
  }
  return out;
}

// ═══ Frank's model — ported from framework.html / forecast.py ═══════════════
// The arithmetic below is Frank's, unchanged, so the "Botify GSC + BWT" basis
// reproduces his headline to the digit (1,843,988 / 7,291,533 / 16,325,245 clicks
// to 31 Dec; 1,418,146 / 5,980,799 / 13,653,665 to 20 Dec; $6.78M / $57.82M).
const FD = P.frank;
function bucketWeights(cfg) {
  const anon = FD.weights.anon * cfg.anon, total = FD.weights.measured + anon;
  return total ? [FD.weights.measured / total, anon / total] : [1, 0];
}
function seasonality(cfg) {
  const [wNb, wAn] = bucketWeights(cfg); const out = {impressions: {}, clicks: {}};
  for (const metric of ['impressions', 'clicks']) for (let m = 1; m <= 12; m++)
    out[metric][m] = wNb * FD.seas.nonbrand[metric][m] + wAn * FD.seas.anon[metric][m];
  return out;
}
function annualTargets(cfg) {
  const L = FD.levels, baseImpr = L.measuredNonbrandImpr + L.anonAssignedImpr * cfg.anon;
  const out = {clicks: {}, levers: {}};
  for (const t of TIERS) {
    const trafficImpr = baseImpr * cfg.growth[t], trafficClks = trafficImpr * L.nonbrandCtr;
    const pages = L.poolCrawledNotIndexed * cfg.dial[t], idxClks = pages * cfg.clicksPerPage * cfg.newPagePerf;
    const measuredShare = baseImpr ? L.measuredNonbrandImpr / baseImpr : 1;
    out.levers[t] = {traffic_measured: trafficClks * measuredShare, traffic_anonymized: trafficClks * (1 - measuredShare),
                     indexation: idxClks, bing: cfg.bing ? L.bingClicks[t] : 0};
    out.clicks[t] = sum(Object.values(out.levers[t]));
  }
  return out;
}
function trancheList(cfg) {
  if (cfg.rampWeeks <= 0) return [[0, 1]];
  const step = cfg.rampWeeks * 7 / cfg.tranches, out = [];
  for (let i = 0; i < cfg.tranches; i++) out.push([pyRound(i * step), 1 / cfg.tranches]);
  return out;
}
const PAIR = {low: 'conservative', mid: 'moderate', high: 'aggressive'};
function rampFraction(tier, day) { return day < 0 ? 0 : FD.ramp[PAIR[tier]][Math.min(Math.floor(day / 30), 3)]; }
function rampAt(cfg, tier, day) { let r = 0; for (const [off, w] of trancheList(cfg)) r += w * rampFraction(tier, day - off); return r; }
// Daily incremental Google+Bing clicks from launch to end (inclusive) — the body of
// Frank's weekly_series, emitted at stride 1 as increments rather than a running sum.
function frankDaily(cfg, tier, endISO) {
  const ann = annualTargets(cfg), seas = seasonality(cfg), bseas = FD.seas.bing;
  const bingPart = cfg.bing ? FD.levels.bingClicks[tier] : 0;
  const googBase = (ann.clicks[tier] - bingPart) / 365, bingBase = bingPart / 365;
  const L = dayNum(cfg.launch), D = dayNum(endISO), out = [];
  for (let d = L; d <= D; d++) {
    const ramp = rampAt(cfg, tier, d - L), m = monthOf(d);
    let v = googBase * seas.clicks[m] * ramp; if (bingBase) v += bingBase * bseas.clicks[m] * ramp;
    out.push({n: d, google: googBase * seas.clicks[m] * ramp, bing: bingBase ? bingBase * bseas.clicks[m] * ramp : 0, v});
  }
  return out;
}
function aiBaselineFrank(basis) {
  const A = FD.trajectory.ai, obs = A.weeks, b = basis || 'three_day_mean', cut = b.lastIndexOf('_');
  const kind = cut > 0 ? b.slice(0, cut) : 'three_day', which = cut > 0 ? b.slice(cut + 1) : 'mean';
  const rows = which === 'w16' ? [obs[0]] : which === 'latest' ? [obs[obs.length - 1]] : obs;
  const v = sum(rows.map(w => w[kind].visits)) / rows.length, g = sum(rows.map(w => w[kind].gmv)) / rows.length;
  const allAi = v * 52 * A.ecosystem;
  return {weeklyVisits: v, weeklyGmv: g, rpv: v ? g / v : 0, allAiAnnualVisits: allAi, riskAdjustedVisits: allAi * A.risk, n: rows.length};
}
// Frank's baseline without us: measured monthly actuals (Aug 2025–Jul 2026, indexed by
// calendar month) grown by the measured trend. Returned per day so it can share an
// axis with the Walmart series.
function frankBaselineDaily(cfg, trends, endISO) {
  const L = dayNum(cfg.launch), D = dayNum(endISO), out = [];
  const g = FD.trajectory.engines.google.monthly, b = FD.trajectory.engines.bing.monthly;
  for (let d = L; d <= D; d++) {
    const y = yearOf(d), m = monthOf(d), days = dim(y, m);
    const held = (g[m] + (cfg.bing ? b[m] : 0)) / days;
    const base = (g[m] * (1 + trends.google) + (cfg.bing ? b[m] * (1 + trends.bing) : 0)) / days;
    out.push({n: d, held, base});
  }
  return out;
}

// ═══ Walmart-basis model ════════════════════════════════════════════════════
// Same levers, Walmart's denominator. Frank's lift is an absolute count of Google +
// Bing clicks; Walmart counts SEO "PDP++ visits" at ~2.5 per click. Two translations
// are offered and the choice is a control:
//   proportional — Frank's annual incremental clicks ÷ his own Google+Bing annual base
//                  gives a full-coverage lift RATE per tier; that rate is applied to
//                  Walmart's baseline visits day by day, through the same ramp.
//   ratio        — Frank's incremental clicks × the measured visits-per-click ratio
//                  over the last 12 months where both archives overlap.
const FRANK_BASE_CLICKS = FD.trajectory.engines.combined.total;   // 757,571,797 Aug25–Jul26
function visitsPerClick() {
  // Overlap: Walmart SEO visits vs GSC total + Bing, trailing 365 days to Bing's last day.
  const to = LAST_BING, from = isoOf(dayNum(to) - 364);
  const v = WM.seo.visits.sum(from, to), c = GSC.total.sum(from, to) + BING.clicks.sum(from, to);
  return {ratio: c ? v / c : 0, from, to, visits: v, clicks: c};
}
const VPC = visitsPerClick();

// Walmart's draft baseline clause: four monthly visit figures for Sep–Dec 2026,
// "established by applying a year-over-year run-rate methodology". Incremental
// visits under the clause = actual − these figures, measured in Walmart's system.
const WB = P.walmartBaseline;
const WB_MONTHS = ['2026-09', '2026-10', '2026-11', '2026-12'];
function wbImplied() {
  const proposed = sum(WB_MONTHS.map(k => WB[k]));
  const ly = WM.seo.visits.sum(isoOf(dayNum('2026-09-01') - YOY), isoOf(dayNum('2026-12-31') - YOY));
  return {proposed, ly, growth: ly ? proposed / ly - 1 : 0};
}
const WBI = wbImplied();

// The trend applied to last year's aligned window. Every option is measured from
// Walmart's own export; "gsc" borrows Frank's Google figure so the two bases can be
// compared on one trend.
function wmTrendOptions(preLaunchISO) {
  const V = WM.seo.visits, end = preLaunchISO;
  return {
    ttm:  {label: 'Trailing 12 months YoY', v: yoyWindow(V, end, 364).change, note: 'Visits, 364 days to ' + end + ' vs the aligned prior year.'},
    t91:  {label: 'Trailing 13 weeks YoY',  v: yoyWindow(V, end, 91).change,  note: 'Visits, 91 days to ' + end + '. The most recent read that spans a full quarter.'},
    t28:  {label: 'Trailing 4 weeks YoY',   v: yoyWindow(V, end, 28).change,  note: 'Visits, 28 days to ' + end + '. Noisy; shown for the direction of travel.'},
    flat: {label: 'Held flat (0%)',         v: 0,                              note: 'Last year’s aligned window, unchanged.'},
    walmart: {label: 'Walmart’s proposed baseline', v: WBI.growth,             note: 'The growth Walmart’s four monthly figures imply against last year’s aligned days (' + fmtC(WBI.proposed) + ' vs ' + fmtC(WBI.ly) + '). Matches August’s year-over-year almost exactly.'},
    gsc:  {label: "Frank's GSC trend",     v: FD.trajectory.engines.google.trend, note: 'Google Search Console clicks, −10.8% on 299 comparable days. Applied here only to show what the GSC trend does to Walmart’s base.'},
  };
}
function wmRpvOptions(preLaunchISO) {
  const G = WM.seo.gmv, V = WM.seo.visits, end = preLaunchISO;
  const r91 = ratioYoy(G, V, end, 91), r364 = ratioYoy(G, V, end, 364);
  return {
    lyTrend364: {label: 'Last year’s month × 12-mo RPV growth', v: r364.change, flat: null,
                 note: 'Same month last year’s GMV per visit, grown by the trailing-12-month change in GMV per visit (' + pct1(r364.change) + '). Keeps the Nov/Dec seasonal lift.'},
    lyTrend91:  {label: 'Last year’s month × 13-wk RPV growth', v: r91.change, flat: null,
                 note: 'Same as above but grown by the trailing-13-week change (' + pct1(r91.change) + '). The upside read: GMV per visit has risen every month since May.'},
    t91flat:    {label: 'Trailing 13-week RPV, flat', v: null, flat: r91.recent,
                 note: 'GMV per visit over the 91 days to ' + end + ' (' + fmtUSD2(r91.recent) + '), held through the window. Ignores the holiday lift in GMV per visit.'},
    ly:         {label: 'Last year’s month, no growth', v: 0, flat: null, note: 'Same month last year’s GMV per visit, unchanged.'},
    frozen:     {label: 'Contract frozen RPV', v: null, flat: null, frozen: true,
                 note: 'Frank’s AOV × CR. The addendum measures revenue at this figure; Walmart’s own ledger will not.'},
  };
}
// GMV per visit for the same calendar month last year (364-day aligned).
function lyMonthRpv(n) {
  const ly = n - YOY, y = yearOf(ly), m = monthOf(ly);
  const a = y + '-' + String(m).padStart(2, '0') + '-01', b = y + '-' + String(m).padStart(2, '0') + '-' + String(dim(y, m)).padStart(2, '0');
  const g = WM.seo.gmv.sum(a, b), v = WM.seo.visits.sum(a, b);
  return v ? g / v : 0;
}

// AEO: Walmart's own AI channel. Baseline is the trailing 28 days before launch;
// the two-week scorecard Frank had is now 19 weeks of export.
function aeoBaseline(preLaunchISO) {
  const to = preLaunchISO, from = isoOf(dayNum(to) - 27);
  const v = WM.aeo.visits.sum(from, to), g = WM.aeo.gmv.sum(from, to), o = WM.aeo.orders.sum(from, to);
  const f91 = isoOf(dayNum(to) - 90), v91 = WM.aeo.visits.sum(f91, to), g91 = WM.aeo.gmv.sum(f91, to), o91 = WM.aeo.orders.sum(f91, to);
  // Linear continuation: average weekly increment over the trailing 8 full weeks.
  const wk = weeklySat({v: WM.aeo.visits}, isoOf(dayNum(to) - 55), to).filter(w => w.days === 7);
  const slope = wk.length >= 2 ? (wk[wk.length - 1].v - wk[0].v) / (wk.length - 1) : 0;   // visits per week per week
  return {dailyVisits: v / 28, weeklyVisits: v / 4, from, to, rpv28: v ? g / v : 0,
          rpv91: v91 ? g91 / v91 : 0, cr91: v91 ? o91 / v91 : 0, aov91: o91 ? g91 / o91 : 0,
          weeklySlope: slope, weeksFit: wk.length};
}

// ═══ formatters ═════════════════════════════════════════════════════════════
const fmtUSD = n => { if (!isFinite(n)) return '—'; const a = Math.abs(n), s = n < 0 ? '−' : '';
  if (a >= 1e9) return s + '$' + (a / 1e9).toFixed(2) + 'B'; if (a >= 1e6) return s + '$' + (a / 1e6).toFixed(a >= 1e8 ? 0 : a >= 1e7 ? 1 : 2) + 'M';
  if (a >= 1e3) return s + '$' + Math.round(a / 1e3) + 'K'; return s + '$' + Math.round(a); };
const fmtUSD2 = n => isFinite(n) ? '$' + n.toFixed(2) : '—';
const fmtC = n => { if (!isFinite(n)) return '—'; const a = Math.abs(n), s = n < 0 ? '−' : '';
  if (a >= 1e9) return s + (a / 1e9).toFixed(2) + 'B'; if (a >= 1e6) return s + (a / 1e6).toFixed(a >= 1e8 ? 0 : 1) + 'M';
  if (a >= 1e4) return s + Math.round(a / 1e3) + 'K'; if (a >= 1e3) return s + (a / 1e3).toFixed(1) + 'K'; return s + Math.round(a); };
const fmtInt = n => isFinite(n) ? Math.round(n).toLocaleString('en-US') : '—';
const pct1 = x => x == null || !isFinite(x) ? '—' : (x * 100).toFixed(1) + '%';
const pct2 = x => x == null || !isFinite(x) ? '—' : (x * 100).toFixed(2) + '%';
const spct = x => x == null || !isFinite(x) ? '—' : (x > 0 ? '+' : x < 0 ? '−' : '') + Math.abs(x * 100).toFixed(1) + '%';
const deltaCls = x => x > 0.0005 ? 'up' : x < -0.0005 ? 'down' : 'flat';
const fmtDate = iso => { const [y, m, d] = iso.split('-'); return +d + ' ' + MON[+m - 1] + ' ' + y; };
const fmtDateS = iso => { const [y, m, d] = iso.split('-'); return +d + ' ' + MON[+m - 1]; };

// ═══ state ══════════════════════════════════════════════════════════════════
const DEFAULTS = {
  tab: 'forecast', basis: 'walmart', horizon: '2026-12-20', launch: '2026-09-01', tier: 'mid',
  wmTrend: 't91', wmTrendCustom: -3.9, rpvMethod: 'lyTrend364', liftMethod: 'proportional',
  aeoInclude: true, aeoTrend: 'flat', aeoRisk: true, aeoEco: 1.0, aeoRpv: 'wm91',
  rampWeeks: 3, tranches: 3,
  anon: 70, growthLo: 7, growthHi: 20, dialLo: 25, dialHi: 60, newPagePerf: 25,
  aov: 74.1, cr: 4.3, bing: true, includeAi: true, aiBasis: 'three_day_mean',
  trendGoogle: -10.8, trendBing: -4.2,
  yoyMetric: 'visits', deltaView: 'yoy',
};
let S = Object.assign({}, DEFAULTS);
try { const saved = JSON.parse(localStorage.getItem('wm-rebase-state') || 'null'); if (saved && typeof saved === 'object') S = Object.assign({}, DEFAULTS, saved); } catch (e) {}
function persist() { try { localStorage.setItem('wm-rebase-state', JSON.stringify(S)); } catch (e) {} }

function cfgFromState() {
  return {launch: S.launch, decision: S.horizon, rampWeeks: S.rampWeeks, tranches: S.tranches, anon: S.anon / 100,
    growth: {low: S.growthLo / 100, high: S.growthHi / 100, mid: (S.growthLo + S.growthHi) / 200},
    dial: {low: S.dialLo / 100, high: S.dialHi / 100, mid: (S.dialLo + S.dialHi) / 200},
    newPagePerf: S.newPagePerf / 100, clicksPerPage: FD.defaults.clicksPerPage, rpv: S.aov * S.cr / 100,
    bing: S.bing, includeAi: S.includeAi, aiBasis: S.aiBasis};
}
const trendsFromState = () => ({google: S.trendGoogle / 100, bing: S.trendBing / 100, ai: 0});

// ═══ derive: one object with everything the views read ══════════════════════
function derive() {
  const cfg = cfgFromState(), trends = trendsFromState();
  const L = dayNum(S.launch), H = dayNum(S.horizon), span = H - L + 1;
  const preLaunch = isoOf(Math.min(L - 1, dayNum(LAST_WM)));
  const lyFrom = isoOf(L - YOY), lyTo = isoOf(H - YOY);

  // ── Botify basis (Frank) ─────────────────────────────────────────────────
  const fb = frankBaselineDaily(cfg, trends, S.horizon);
  const aiF = aiBaselineFrank(S.aiBasis);
  const bt = {};
  for (const t of TIERS) {
    const inc = frankDaily(cfg, t, S.horizon);
    const aiDaily = aiF.riskAdjustedVisits * FD.trajectory.ai.lift[t] / 365;
    let cumClicks = 0, cumRev = 0, cumAi = 0, cumAiRev = 0; const daily = [];
    inc.forEach((p, i) => {
      const ramp = rampAt(cfg, t, p.n - L), ai = aiDaily * ramp;
      cumClicks += p.v; cumRev += p.v * cfg.rpv; cumAi += ai; cumAiRev += ai * aiF.rpv;
      daily.push({n: p.n, base: fb[i].base, held: fb[i].held, inc: p.v, incRev: p.v * cfg.rpv, ai, aiRev: ai * aiF.rpv, cumRev, cumAiRev, cumTotal: cumRev + (cfg.includeAi ? cumAiRev : 0)});
    });
    const baseClicks = sum(fb.map(p => p.base)), heldClicks = sum(fb.map(p => p.held));
    const lyClicks = frankLyWindow(cfg, lyFrom, lyTo);
    bt[t] = {daily, incVisits: cumClicks, searchRev: cumRev, aiVisits: cumAi, aiRev: cumAiRev,
             totalRev: cumRev + (cfg.includeAi ? cumAiRev : 0),
             baseVisits: baseClicks, heldVisits: heldClicks, withUs: baseClicks + cumClicks, lyVisits: lyClicks,
             baseYoy: lyClicks ? baseClicks / lyClicks - 1 : null, withUsYoy: lyClicks ? (baseClicks + cumClicks) / lyClicks - 1 : null,
             liftPct: baseClicks ? cumClicks / baseClicks : 0, exit: rampAt(cfg, t, span - 1), rpv: cfg.rpv,
             aiBaseVisits: aiF.allAiAnnualVisits / 365 * span, aiRpv: aiF.rpv};
  }

  // ── Walmart basis ────────────────────────────────────────────────────────
  const trendOpts = wmTrendOptions(preLaunch);
  const trend = S.wmTrend === 'custom' ? S.wmTrendCustom / 100 : (trendOpts[S.wmTrend].v || 0);
  const rpvOpts = wmRpvOptions(preLaunch), rpvOpt = rpvOpts[S.rpvMethod];
  const rpvAt = n => rpvOpt.frozen ? cfg.rpv : rpvOpt.flat != null ? rpvOpt.flat : lyMonthRpv(n) * (1 + (rpvOpt.v || 0));
  const ann = annualTargets(cfg);
  const aeoB = aeoBaseline(preLaunch);
  const aeoRpv = S.aeoRpv === 'wm91' ? aeoB.rpv91 : S.aeoRpv === 'wm28' ? aeoB.rpv28 : aiF.rpv;
  const aeoRisk = S.aeoRisk ? FD.trajectory.ai.risk : 1;
  const wm = {};
  for (const t of TIERS) {
    const liftRate = ann.clicks[t] / FRANK_BASE_CLICKS;      // full-coverage lift, as a share of the base
    const fInc = S.liftMethod === 'ratio' ? frankDaily(cfg, t, S.horizon) : null;
    let cumV = 0, cumRev = 0, cumAi = 0, cumAiRev = 0, baseV = 0, baseG = 0, lyV = 0, lyG = 0, aeoBaseV = 0; const daily = [];
    for (let d = L, i = 0; d <= H; d++, i++) {
      const ly = WM.seo.visits.getN(d - YOY) || 0, lyg = WM.seo.gmv.getN(d - YOY) || 0;
      const base = ly * (1 + trend), rpv = rpvAt(d), ramp = rampAt(cfg, t, d - L);
      const inc = S.liftMethod === 'ratio' ? fInc[i].v * VPC.ratio : base * liftRate * ramp;
      // AEO baseline: flat or linear continuation of the trailing-8-week slope
      const weeksOut = (d - L + 1) / 7, aeoBase = aeoB.dailyVisits + (S.aeoTrend === 'linear' ? aeoB.weeklySlope * weeksOut / 7 : 0);
      const ai = aeoBase * FD.trajectory.ai.lift[t] * aeoRisk * S.aeoEco * ramp;
      cumV += inc; cumRev += inc * rpv; cumAi += ai; cumAiRev += ai * aeoRpv; baseV += base; baseG += base * rpv; lyV += ly; lyG += lyg; aeoBaseV += aeoBase;
      daily.push({n: d, ly, lyGmv: lyg, base, baseGmv: base * rpv, rpv, inc, incRev: inc * rpv, ai, aiRev: ai * aeoRpv, aeoBase, cumRev, cumAiRev, cumTotal: cumRev + (S.aeoInclude ? cumAiRev : 0)});
    }
    wm[t] = {daily, incVisits: cumV, searchRev: cumRev, aiVisits: cumAi, aiRev: cumAiRev, totalRev: cumRev + (S.aeoInclude ? cumAiRev : 0),
             baseVisits: baseV, baseGmv: baseG, lyVisits: lyV, lyGmv: lyG, withUs: baseV + cumV,
             baseYoy: lyV ? baseV / lyV - 1 : null, withUsYoy: lyV ? (baseV + cumV) / lyV - 1 : null,
             liftPct: baseV ? cumV / baseV : 0, liftRate, exit: rampAt(cfg, t, span - 1), rpv: baseV ? baseG / baseV : 0,
             aiBaseVisits: aeoBaseV, aiRpv: aeoRpv};
  }

  // ── measured against Walmart's proposed baseline ─────────────────────────
  // The clause is monthly, so December is pro-rated by last year's aligned share of
  // the month falling inside the window when the horizon is the 20th.
  const wb = {rows: [], totals: {}};
  for (const key of WB_MONTHS) {
    const y = +key.slice(0, 4), m = +key.slice(5, 7), a = dayNum(key + '-01'), b = a + dim(y, m) - 1;
    const wa = Math.max(a, L), wz = Math.min(b, H); if (wz < wa) continue;
    let lyFull = 0; for (let d = a; d <= b; d++) lyFull += WM.seo.visits.getN(d - YOY) || 0;
    const row = {y, m, days: wz - wa + 1, fullDays: b - a + 1, proposedFull: WB[key], ly: 0, base: 0, with: {}, inc: {}};
    TIERS.forEach(t => { row.with[t] = 0; row.inc[t] = 0; });
    for (let d = wa; d <= wz; d++) {
      const i = d - L; row.ly += wm.mid.daily[i].ly; row.base += wm.mid.daily[i].base;
      TIERS.forEach(t => { row.inc[t] += wm[t].daily[i].inc; row.with[t] += wm[t].daily[i].base + wm[t].daily[i].inc; });
    }
    row.proposed = lyFull ? WB[key] * row.ly / lyFull : WB[key] * row.days / row.fullDays;
    row.impliedGrowth = row.ly ? row.proposed / row.ly - 1 : null;
    row.gapWithout = row.base - row.proposed;
    row.gapWith = {}; TIERS.forEach(t => row.gapWith[t] = row.with[t] - row.proposed);
    wb.rows.push(row);
  }
  const T = wb.totals; T.proposed = sum(wb.rows.map(r => r.proposed)); T.ly = sum(wb.rows.map(r => r.ly)); T.base = sum(wb.rows.map(r => r.base));
  T.gapWithout = T.base - T.proposed; T.with = {}; T.gapWith = {}; T.inc = {};
  TIERS.forEach(t => { T.with[t] = sum(wb.rows.map(r => r.with[t])); T.gapWith[t] = T.with[t] - T.proposed; T.inc[t] = sum(wb.rows.map(r => r.inc[t])); });
  T.impliedGrowth = T.ly ? T.proposed / T.ly - 1 : null;
  // Trend at which the with-Botify path exactly meets the clause, per tier.
  T.breakeven = {}; TIERS.forEach(t => T.breakeven[t] = T.ly ? T.proposed / (T.ly + T.inc[t] / (1 + trend)) - 1 : null);
  wb.implied = WBI;
  // cumulative measured incremental (actual with Botify − clause), by day, per tier
  wb.cum = {}; TIERS.forEach(t => { let c = 0; wb.cum[t] = wm[t].daily.map(p => { const key = yearOf(p.n) + '-' + String(monthOf(p.n)).padStart(2, '0'); const r = wb.rows.find(x => x.y === yearOf(p.n) && x.m === monthOf(p.n)); const share = r && r.ly ? p.ly / r.ly * r.proposed : 0; c += p.base + p.inc - share; return {n: p.n, v: c}; }); });

  // ── first week of actuals (Walmart, plus GSC now that the pull runs to 6 Sep) ──
  const actTo = LAST_WM, actuals = dayNum(actTo) >= L ? (() => {
    const a = S.launch, b = actTo, v = WM.seo.visits.sum(a, b), g = WM.seo.gmv.sum(a, b), o = WM.seo.orders.sum(a, b);
    const lyv = WM.seo.visits.sum(isoOf(L - YOY), isoOf(dayNum(b) - YOY)), lyg = WM.seo.gmv.sum(isoOf(L - YOY), isoOf(dayNum(b) - YOY));
    const days = dayNum(b) - L + 1, base = lyv * (1 + trend);
    const expected = {}; TIERS.forEach(t => expected[t] = sum(wm[t].daily.slice(0, days).map(p => p.inc)));
    const aeoV = WM.aeo.visits.sum(a, b), aeoG = WM.aeo.gmv.sum(a, b), aeoBase = aeoB.dailyVisits * days;
    let gsc = null;
    if (dayNum(LAST_GSC) >= L) { const gb = LAST_GSC, gv = GSC.total.sum(a, gb), gly = GSC.total.sum(isoOf(L - YOY), isoOf(dayNum(gb) - YOY)); gsc = {to: gb, days: dayNum(gb) - L + 1, clicks: gv, yoy: gly ? gv / gly - 1 : null, nonbrand: GSC.nonbrand.sum(a, gb), nbYoy: (() => { const p = GSC.nonbrand.sum(isoOf(L - YOY), isoOf(dayNum(gb) - YOY)); return p ? GSC.nonbrand.sum(a, gb) / p - 1 : null; })()}; }
    return {from: a, to: b, days, visits: v, gmv: g, orders: o, lyVisits: lyv, lyGmv: lyg, base, vsBase: base ? v / base - 1 : null, yoy: lyv ? v / lyv - 1 : null, gmvYoy: lyg ? g / lyg - 1 : null, expected, aeoV, aeoG, aeoBase, gsc};
  })() : null;

  return {cfg, trends, L, H, span, preLaunch, lyFrom, lyTo, bt, wm, wb, trend, trendOpts, rpvOpts, rpvOpt, aeoB, aeoRpv, aeoRisk, aiF, ann, actuals, vpc: VPC};
}
// Frank's monthlyFull gives Google+Bing property totals by calendar month back to
// Nov 2024 (Google) / Apr 2025 (Bing); prorate them over last year's aligned window.
function frankLyWindow(cfg, from, to) {
  let t = 0; const MF = FD.trajectory.monthlyFull;
  for (let n = dayNum(from); n <= dayNum(to); n++) {
    const y = yearOf(n), m = monthOf(n), key = y + '-' + String(m).padStart(2, '0');
    const g = MF.google[key], b = MF.bing[key];
    if (g) t += g.total / g.days; if (cfg.bing && b) t += b.total / b.days;
  }
  return t;
}
